# Generated by Django 4.1.3 on 2023-02-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0002_remove_movement_report'),
        ('report', '0002_alter_historicalreport_options_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='movement',
            field=models.ManyToManyField(blank=True, null=True, to='movement.movement'),
        ),
    ]
